version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build --no-cache --pull -t ${ECR_REPOSITORY_URI}:latest .
      - echo "Checking Docker ENTRYPOINT and CMD for debugging..."
      - docker inspect ${ECR_REPOSITORY_URI}:latest -f '{{json .Config.Entrypoint}}'
      - docker inspect ${ECR_REPOSITORY_URI}:latest -f '{{json .Config.Cmd}}'

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push ${ECR_REPOSITORY_URI}:latest
      - echo "[{\"name\":\"loginapp\",\"imageUri\":\"${ECR_REPOSITORY_URI}:latest\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
  discard-paths: yes
