version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --no-cache --pull -t ${ECR_REPOSITORY_URI}:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY_URI}:latest
  
      # Generate imagedefinitions.json dynamically
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"loginapp","imageUri":"%s"}]' ${ECR_REPOSITORY_URI}:latest > imagedefinitions.json
  
      # Debugging: Check the content of taskdef.json before registering
      - echo "Validating taskdef.json content..."
      - cat taskdef.json
  
      # Validate JSON syntax before registration
      - echo "Checking JSON syntax..."
      - jq empty taskdef.json || (echo "ERROR: taskdef.json is not valid JSON!" && exit 1)
  
      # Register the new task definition revision
      - echo Registering new task definition...
      - aws ecs register-task-definition --cli-input-json file://taskdef.json || (echo "ERROR: Task definition registration failed!" && exit 1)
  
      # Fetch the new task definition ARN
      - echo Fetching latest task definition ARN...
      - TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition login-app --query "taskDefinition.taskDefinitionArn" --output text)
  
      # Create updated AppSpec file with new task definition ARN
      - echo Writing updated AppSpec file...
      - |
        cat << EOF > appspec.yaml
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: <TASK_DEFINITION>
                LoadBalancerInfo:
                  ContainerName: "loginapp"
                  ContainerPort: 80
                PlatformVersion: "LATEST"
        EOF
  
      # Display generated files for debugging
      - cat imagedefinitions.json
      - cat taskdef.json
      - cat appspec.yaml
      
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.nuget/**/*'
