version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  
  build:
    commands:
      - echo "Build started on $(date)"
      - docker build --no-cache --pull -t ${ECR_REPOSITORY_URI}:latest .
  
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - docker push ${ECR_REPOSITORY_URI}:latest
      - echo "[{\"name\":\"loginapp\",\"imageUri\":\"${ECR_REPOSITORY_URI}:latest\"}]" > imagedefinitions.json

      # Replace variables in taskdef.json
      - sed -i "s|\${ECR_REPOSITORY_URI}|${ECR_REPOSITORY_URI}|g" taskdef.json
      - sed -i "s|\${AWS_DEFAULT_REGION}|${AWS_DEFAULT_REGION}|g" taskdef.json
      - sed -i "s|\${ECS_EXECUTION_ROLE_ARN}|${ECS_EXECUTION_ROLE_ARN}|g" taskdef.json
      - sed -i "s|\${ECS_TASK_ROLE_ARN}|${ECS_TASK_ROLE_ARN}|g" taskdef.json

      # Register task definition properly
      - echo "Registering new task definition..."
      - |
        TASK_DEFINITION=$(aws ecs register-task-definition --cli-input-json file://taskdef.json --query "taskDefinition.taskDefinitionArn" --output text)
        echo "TASK_DEFINITION=$TASK_DEFINITION"
        if [[ -z "$TASK_DEFINITION" ]]; then echo "ERROR: Task definition registration failed!" && exit 1; fi

      # Create updated AppSpec file with new task definition ARN (Fixed YAML formatting)
      - echo "Creating updated AppSpec file..."
      - |
        cat <<EOF > appspec.yaml
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "$TASK_DEFINITION"
                LoadBalancerInfo:
                  ContainerName: "loginapp"
                  ContainerPort: 80
                PlatformVersion: "LATEST"
        EOF

      # Display generated files for debugging
      - cat imagedefinitions.json
      - cat appspec.yaml
      - cat taskdef.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
  discard-paths: yes

cache:
  paths:
    - '/root/.nuget/**/*'
